name: Build AMI with Packer

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-ami:
    runs-on: ubuntu-latest
    environment:
      name: AWS_DEPLOYMENT

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Root Directory and Move Zip to packer folder
        run: |
          zip -r webapp.zip . -x "packer/*" -x "infrastructure/*" -x "grader/*" -x ".github/*" -x ".git/*"
          mv webapp.zip packer/

      - name: Create and move credentials file
        run: |
          cat <<'EOF' > credentials
          [AmazonCloudWatchAgent]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          mv credentials packer/scripts/

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: '1.12.0'

      - name: Packer Init
        run: |
          cd packer
          packer init .

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Packer Validate
        run: |
          cd packer
          packer validate .

      - name: Packer Build
        run: |
          cd packer
          packer build . | tee packer_build_output.log

      - name: Extract AMI IDs
        id: get_ami_ids
        run: |
          MYSQL_AMI=$(grep -A 1 "amazon-ebs.mysql: AMIs were created:" packer/packer_build_output.log | grep -oP 'ami-[a-zA-Z0-9]+')
          WEBAPP_AMI=$(grep -A 1 "amazon-ebs.webapp: AMIs were created:" packer/packer_build_output.log | grep -oP 'ami-[a-zA-Z0-9]+')

          [ -z "$MYSQL_AMI" ] && { echo "Error: MYSQL AMI ID is empty"; exit 1; }
          [ -z "$WEBAPP_AMI" ] && { echo "Error: WEBAPP AMI ID is empty"; exit 1; }

          echo "MYSQL AMI ID is $MYSQL_AMI"
          echo "WEBAPP AMI ID is $WEBAPP_AMI"
