name: Continuous Deployment

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS_DEPLOYMENT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Delete existing stack (if any)
        run: |
          aws cloudformation describe-stacks --stack-name vpc && \
          aws cloudformation delete-stack --stack-name vpc && \
          aws cloudformation wait stack-delete-complete --stack-name vpc || \
          echo "No existing stack to delete."

      - name: Create VPC and Subnets
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          aws cloudformation create-stack \
            --stack-name vpc \
            --template-body file://infrastructure/vpc.yaml \
            --parameters \
              ParameterKey=DBUser,ParameterValue=$DB_USER \
              ParameterKey=DBPassword,ParameterValue=$DB_PASSWORD \
              ParameterKey=DBName,ParameterValue=$DB_NAME \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Wait for stack creation to complete
        run: |
          aws cloudformation wait stack-create-complete --stack-name vpc

      - name: Get stack outputs
        id: get-outputs
        run: |
          aws cloudformation describe-stacks --stack-name vpc --query "Stacks[0].Outputs" > stack-outputs.json
          # cat stack-outputs.json

      - name: Extract WebApp Public IP, Database Private IP, and Database Instance ID
        id: extract_ips
        run: |
          WEBAPP_PUBLIC_IP=$(jq -r '.[] | select(.OutputKey=="WebAppPublicIP") | .OutputValue' stack-outputs.json)
          DATABASE_PRIVATE_IP=$(jq -r '.[] | select(.OutputKey=="DatabasePrivateIP") | .OutputValue' stack-outputs.json)
          DATABASE_INSTANCE_ID=$(jq -r '.[] | select(.OutputKey=="DatabaseInstanceId") | .OutputValue' stack-outputs.json)
          echo "PUBLIC_IP=$WEBAPP_PUBLIC_IP" >> $GITHUB_ENV
          echo "DATABASE_PRIVATE_IP=$DATABASE_PRIVATE_IP" >> $GITHUB_ENV
          echo "DATABASE_INSTANCE_ID=$DATABASE_INSTANCE_ID" >> $GITHUB_ENV

      - name: Use WebApp Public IP and Database Private IP
        run: |
          echo "The WebApp Public IP is ${{ env.PUBLIC_IP }}"
          echo "The Database Private IP is ${{ env.DATABASE_PRIVATE_IP }}"
          echo "The Database Instance ID is ${{ env.DATABASE_INSTANCE_ID }}"

      - name: Attach EBS Volume to Database EC2
        env:
          VOLUME_ID: ${{ secrets.EBS_VOLUME_ID }}
        run: |
          aws ec2 attach-volume \
            --volume-id $VOLUME_ID \
            --instance-id ${{ env.DATABASE_INSTANCE_ID }} \
            --device /dev/sdf

          echo "Attached EBS Volume $VOLUME_ID to Database EC2"

      - name: Configure EBS Volume on Database EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ env.PUBLIC_IP }}
          SSH_USER: ${{ vars.SSH_USER }}
        run: |
          echo "Copy SSH key to runner"
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          echo "Copying all files from root to EC2..."
          scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* $SSH_USER@$SSH_HOST:/home/ubuntu/app/

          echo "Configure EBS on Database EC2..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            ssh -o StrictHostKeyChecking=no -i app/ec2_key.pem $SSH_USER@${{ env.DATABASE_PRIVATE_IP }} << 'INNER_EOF'
              echo "Connected to Database EC2 instance"

              # Check if EBS volume is mounted
              if lsblk | grep xvdf; then
                  echo "EBS volume detected."
              else
                  echo "EBS volume not detected. Exiting..."
                  exit 1
              fi

              # Mount EBS volume
              sudo mkdir -p /mnt/mysql-data
              sudo mount /dev/xvdf /mnt/mysql-data
              echo "/dev/xvdf /mnt/mysql-data ext4 defaults,nofail 0 2" | sudo tee -a /etc/fstab

              # Set permissions
              sudo chown -R mysql:mysql /mnt/mysql-data

              # Restart MySQL service
              sudo systemctl stop mysql
              sudo systemctl start mysql
              echo "MySQL is running with EBS Volume."
            INNER_EOF
            # delete the key from the EC2 instance for security
            rm -f app/ec2_key.pem
          EOF

      - name: Setup environment on EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ env.PUBLIC_IP }}
          SSH_USER: ${{ vars.SSH_USER }}
        run: |
          # echo "Copy SSH key to runner"
          # echo "$EC2_SSH_KEY" > ec2_key.pem
          # chmod 600 ec2_key.pem

          # echo "Copying all files from root to EC2..."
          # scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* $SSH_USER@$SSH_HOST:/home/ubuntu/app/

          echo "Setting up environment on EC2..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            echo "Changing to app directory..."
            cd /home/ubuntu/app

            echo "Installing necessary packages..."
            sudo apt-get update
            sudo apt-get install -y python3-venv python3-pip

            echo "Creating and activating virtual environment..."
            python3 -m venv venv
            source venv/bin/activate

            echo "Installing required Python packages..."
            pip install -r requirements.txt

            echo "Setup completed."
          EOF

      - name: Create and copy .env file to EC2
        run: |
          echo "Creating .env file..."
          echo "DB_HOST=${{ env.DATABASE_PRIVATE_IP }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "FLASK_SECRET=${{ secrets.FLASK_SECRET }}" >> .env
          cat .env

          echo "Copying .env file to EC2..."
          scp -o StrictHostKeyChecking=no -i ec2_key.pem .env $SSH_USER@$SSH_HOST:/home/ubuntu/app/

      # - name: Ingest movies data
      #   env:
      #     EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     SSH_HOST: ${{ env.PUBLIC_IP }}
      #     SSH_USER: ${{ vars.SSH_USER }}
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i ec2_key.pem $SSH_USER@$SSH_HOST << 'EOF'
      #       echo "Changing to app directory..."
      #       cd /home/ubuntu/app

      #       echo "Activating virtual environment..."
      #       source venv/bin/activate

      #       echo "Running ingestion script..."
      #       python scripts/movies_ingest.py

      #       echo "Ingestion completed."
      #     EOF

      - name: launch Web App to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ env.PUBLIC_IP }}
          SSH_USER: ${{ vars.SSH_USER }}
        run: |
          echo "Starting Flask app..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            echo "Changing to app directory..."
            cd /home/ubuntu/app

            echo "Activating virtual environment..."
            source venv/bin/activate

            nohup python run.py > app.log 2>&1 &
            exit
          EOF

      - name: Setup Variables for Grader Workflow
        run: |
          echo "SSH_HOST=${{ env.PUBLIC_IP }}" > grader-env.txt
          echo "SSH_USER=${{ vars.SSH_USER }}" >> grader-env.txt
          echo "WEBAPP_HOST=${{ env.PUBLIC_IP }}" > grader-env.txt
          echo "WEBAPP_USER=${{ vars.SSH_USER }}" >> grader-env.txt
          echo "MYSQL_PRIVATE_IP=${{ env.DATABASE_PRIVATE_IP }}" >> grader-env.txt
          echo "DATABASE_USER_NAME=${{ secrets.DB_USER }}" >> grader-env.txt
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> grader-env.txt
          # echo "MOVIE_INGEST_COMMAND=./scripts/run_ingestion.sh" >> grader-env.txt

      - name: Upload Grader Environment Variables
        uses: actions/upload-artifact@v4
        with:
          name: grader-env
          path: grader-env.txt
